<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeorgiPeev.Web\GeorgiPeev.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="SkiaSharp" Version="4.152.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Codes\Projects\georgipeev-site\GeorgiPeev.Web.Tests\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Codes\Projects\georgipeev-site\GeorgiPeev.Web.Tests\.editorconfig" />
  </ItemGroup>

</Project>