// <auto-generated />
using System;
using GeorgiPeev.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeorgiPeev.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909191317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeorgiPeev.Web.Features.Concerts.Concert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("TicketUrl")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("ticket_url");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_concerts");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_concerts_slug");

                    b.HasIndex("IsPublished", "StartsAt")
                        .HasDatabaseName("ix_concerts_is_published_starts_at");

                    b.ToTable("concerts", (string)null);
                });

            modelBuilder.Entity("GeorgiPeev.Web.Features.Concerts.Concert", b =>
                {
                    b.OwnsOne("GeorgiPeev.Web.Common.Localized", "City", b1 =>
                        {
                            b1.Property<Guid>("ConcertId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bg")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city_bg");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city_en");

                            b1.HasKey("ConcertId");

                            b1.ToTable("concerts");

                            b1.WithOwner()
                                .HasForeignKey("ConcertId")
                                .HasConstraintName("fk_concerts_concerts_id");
                        });

                    b.OwnsOne("GeorgiPeev.Web.Common.Localized", "Note", b1 =>
                        {
                            b1.Property<Guid>("ConcertId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bg")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("note_bg");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("note_en");

                            b1.HasKey("ConcertId");

                            b1.ToTable("concerts");

                            b1.WithOwner()
                                .HasForeignKey("ConcertId")
                                .HasConstraintName("fk_concerts_concerts_id");
                        });

                    b.OwnsOne("GeorgiPeev.Web.Common.Localized", "Venue", b1 =>
                        {
                            b1.Property<Guid>("ConcertId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bg")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("venue_bg");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("venue_en");

                            b1.HasKey("ConcertId");

                            b1.ToTable("concerts");

                            b1.WithOwner()
                                .HasForeignKey("ConcertId")
                                .HasConstraintName("fk_concerts_concerts_id");
                        });

                    b.Navigation("City")
                        .IsRequired();

                    b.Navigation("Note")
                        .IsRequired();

                    b.Navigation("Venue")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
